language: elixir
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - mix format --check-formatted
  - mix test
matrix:
  include:
    - otp_release: 20.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.1
    - otp_release: 22.0
      elixir: 1.9.1
