language: elixir
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - |
    if [[ "$CHECK_FORMATTED" -eq 1 ]]
    then
      mix format --check-formatted
    else
      echo "Not checking formatting"
    fi
  - mix test
  - |
    if [[ "$RUN_DIALYZER" -eq 1 ]]
    then
      travis_wait 30 mix dialyzer
    else
      echo "Not running Dialyzer"
    fi
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8.2
    - otp_release: 22.3
      elixir: 1.9.4
    - otp_release: 23.0.3
      elixir: 1.10.3
      env:
        - CHECK_FORMATTED=1
        - RUN_DIALYZER=1
