name: Build and Publish docsite

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Mkdocs website
    runs-on: ubuntu-20.04
    strategy:
        max-parallel: 1
    container:
      image: squidfunk/mkdocs-material
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: mkdocs build -s
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site

  publish:
    needs: build
    name: Publish Mkdocs website to GH Pages
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: mkdocs
          publish_dir: site
          github_token: ${{ secrets.GITHUB_TOKEN }}
